# Generated by Django 3.0 on 2020-03-18 02:50

from django.db import migrations, models
import schedules.validators


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.DateField(validators=[schedules.validators.validate_date]),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('doctor', 'day')},
        ),
    ]
